version: '3.1'

services:
  db:
    image: postgres:14.6
    env_file:
      - .env
    restart: always
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: kpomak
      POSTGRES_DB: todo
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    privileged: true
    ports:
      - 8000:8000
    command: bash -c "./config/wait_postgres.sh db && python manage.py migrate && python manage.py createusers && gunicorn config.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8010:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx
